### ISSUE TITLE
[Cheapest Fare(Python) setup] no way to verify if the service is running.

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#42]
ran the commands in the project wiki, server runs on port 8000.
How do i test that its running as it should ? 
you might wanna look into the logs

![image](https://user-images.githubusercontent.com/42894144/52512989-e619f500-2bd5-11e9-899a-ea478e6cd84b.png)

![image](https://user-images.githubusercontent.com/42894144/52513011-0053d300-2bd6-11e9-9e93-77653e10deed.png)

**Comment by alakhsingh** [comment]
@KalaRaja This issue was also linked to the previous DB related issue. There were also few ambiguous python statements in wiki which caused the error, it has been updated now. For this service to work, java service needs to works which at the time you were testing was down. Try it now and let me know of any other issues.
